# Generated by Django 5.0.7 on 2024-07-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_products_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
