# Generated by Django 5.0.7 on 2024-07-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1000)),
                ('product_choice', models.CharField(choices=[('Chair Mechanism', 'Chair Mechanism'), ('Arm Rest', 'Arm Rest'), ('Height Adjustment & Legs', 'Height Adjustment & Legs'), ('Fitting & Accessories', 'Fitting & Accessories'), ('Castor & Adjustment', 'Castor & Adjustment'), ('Plastic Net Back', 'Plastic Net Back'), ('AC & Washing machine stand', 'AC & Washing machine stand'), ('Inner outer & Plastic accessories', 'Inner outer & Plastic accessories'), ('Chair Base', 'Chair Base')], max_length=400)),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('product_description', models.CharField(max_length=10000)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
