# Generated by Django 5.0.7 on 2024-07-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
